apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 4
  template:
    metadata:
      labels:
        app: "go-server"
    spec:
      containers:
        - name: go-server
          image: "gravinawilliam/hello-go:v2"
